### ISSUE TITLE
Details page stylesheet improvements

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#47]
- Do not put the entire page in a card
- Information boxes need to be better visible (full boder with no shadow effect, different background color between box and background)
- Do not use H6 for normal text
- Separation line below headlines should either be 100% width or if they start with a margin on the left they should have the same on the right
- Experiment type, Keyword, Funding source should be the same font level as name and description in sample
- Data files box misses separation line
- Publication should be formatted according to Pubmed. If the bullet points cause trouble remove them and just have some spacing between the papers.

**Comment by Anubhav2201** [comment]
Commit : d5155b59e5e73aac5ad4115c9b9d3342a49fe9e8

Yet to complete:
- Publication should be formatted according to Pubmed. If the bullet points cause trouble remove them and just have some spacing between the papers.
- Do not use H6 for normal text

**Comment by Anubhav2201** [comment]
Opened a new issue for remaining changes
https://github.com/ReneRanzinger/IFEDS-frontend/issues/64
