### ISSUE TITLE
Nested side menu

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#50]
Change the side menu to a nested menu
- Home
- Data
-- Samples
-- Datesets
- Profile
-- Password
-- Account settings
- Administer
-- New user
-- User permission
-- Dictionairies

The Administer menu and its submenu are only shown if the user is an admin (talk to Akshay about how to receive this on login).

**Comment by Jidhnyasa** [comment]
Executed Nested Menu
