### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#51]
After login and when clicking on Home in the side menu:

Card: "Your samples" -> Number of samples -> link to samples
Card: "Your datasets" -> Number of datasets -> link to datasets
Card: "Your Profile "-> Similar to contributor box -> with edit icon that leads to edit user profile page.

**Comment by Anubhav2201** [comment]
Admin Design- Later

**Comment by Anubhav2201** [comment]
Commit : 6781db4b3a7228c55efc9f19b89a60cb8486f081

**Comment by Anubhav2201** [comment]
Done work on frontend. Need to put ws url

**Comment by Anubhav2201** [comment]
Done Changes to adjust backend ws
Commit: ff3acfb541c2314f01fa1a318fb7b05eba39d3a4
