### ISSUE TITLE
List of own datasets page

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#52]
- Headline so that it does not disappear behind the side menu (center?)
- Search field below headline
- Remove Author from the table, they are all mine anyway
- 1-2 whitespace between text and "...read less/more"
- Add column "Number of files" 
- **No option for creating a new dataset is given.**

**Comment by Anubhav2201** [comment]
Commit : e94784c33eb9ac28def9add641dfdfac6fc4fd79

Changes still to make :
- Headline so that it does not disappear behind the side menu (center?)

Note : For --Add column "Number of files"
getProviderDataset ws is not providing number of files information

**Comment by Anubhav2201** [comment]
Done remaining changes.
- Verified getProviderDataset ws for providing number of files information

For remaining changes new issue has been opened
https://github.com/ReneRanzinger/IFEDS-frontend/issues/65
