### ISSUE TITLE
Edit sample 1

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#54]
https://glygen.ccrc.uga.edu/ifeds/editsample/1

- For sample type the placeholder text AND the selection is shown
- here it says "biological" but in the show my samples its listed as "stem cell derived"

1. Add (https://glygen.ccrc.uga.edu/ifeds/editsample/1) into the URL field
2. Save -> error message "Please enter an email".

- for highlighting errors using of red is ok.
- If two fields have errors only the first is highlighted.

**Comment by Anubhav2201** [comment]
Commit for url type : 7bbd93c996be8008de98d70477c04d7e4f0bdc47

**Comment by Anubhav2201** [comment]
Commit for sample type id not displaying correctly
c2c92b6cac11342e1939901a1200ba54bde22d94

**Comment by Anubhav2201** [comment]
For validation : There is already an open issue
https://github.com/ReneRanzinger/IFEDS-frontend/issues/26
