### ISSUE TITLE
Create new sample page

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#55]
- Validation: use red to highlight errors + allow multiple errors to be highlighted
- When clicking add sample descriptor clear the fields, its unlikely that a second descriptor of the same type/value is added.
- Can we make the "Add sample Descriptor" a button, right now nothing happens when clicking it.
- Currently its possible to add the same descriptor (key/value) twice. That is not allowed
- Add some spacing between the descriptor badges
- Add a left margin to avoid the side menu overlapping with the form.
- When adding a URL an error regarding not being an email is shown.
- **When clicking create I am coming back to the sample list but my sample is not there (no error message shown).**

**Comment by Anubhav2201** [comment]
Done except validation and service not working

Commit: 75838728a83101afa4ff1a0568649b1da3392099

The part which is not working: Opening issues:

For Validation
https://github.com/ReneRanzinger/IFEDS-frontend/issues/26

For Service Not working
https://github.com/ReneRanzinger/IFEDS-frontend/issues/69
