### ISSUE TITLE
Edit profile page

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#57]
1. Call profile WS with token
2. Fill profile data into form
3. When submit, validate and send data to updated profile WS
4. Show error or success but stay on page.

**Comment by Anubhav2201** [comment]
Done
Commit : 923b4c7de7fd7c5f6072131bf05c4c8411e0758c , 9d36692a546846c93d045cd7069b8cc5006a5f19
