### ISSUE TITLE
User permission page

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#59]
1. Get all users and their permission from the data
2. Show in table with username, email, admin, disabled and action column (except current user)
- Action colum: if user is admin -> Remove admin privilegdes; is user is not admin -> promote to admin; if users is enabled -> disable user (not for admins); if user is disabled -> enable user
3. Call update user permission WS and show error or success

**Comment by Anubhav2201** [comment]
Done
Commit: 635c44c0a6412d611299e577d75c0a769aa6a9a7
