### ISSUE TITLE
Detail page stylesheet improvement

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-frontend#64]
- Publication should be formatted according to Pubmed. If the bullet points cause trouble remove them and just have some spacing between the papers.
- Do not use H6 for normal text

**Comment by ReneRanzinger** [comment]
The background should be fixed. Right now the page has a white background. On top is gray box for the main area on which the white info boxes are placed. Merge the first two backgrounds into one (white+gray). Using gray color is fine but it should fill the entire page. Also keep in mind that should be the same color for ALL pages.

With regards to color and also box border style take a look at this (https://glygen.ccrc.uga.edu/glygen/). But this part has low priority.

**Comment by Anubhav2201** [comment]
Partially complete .
Commit: 7f0949210f64ca465587a557f31b1e10415c2664

**Comment by Anubhav2201** [comment]
Created new ticket for second part
https://github.com/ReneRanzinger/IFEDS-frontend/issues/74
