### ISSUE TITLE
Add list of descriptors column (can you use the tags there?) In List of Own Samples

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-frontend#66]
Waiting for Backend ticket to be resolved: https://github.com/ReneRanzinger/IFEDS-backend/issues/78

**Comment by akshaykokane** [comment]
**Resolved at backend**

https://github.com/ReneRanzinger/IFEDS-backend/issues/78#issuecomment-621566845

**Comment by Anubhav2201** [comment]
Completed
Commit: 308b15251cb7d07ec59ce0018a754129c209780e
