### ISSUE TITLE
Dashbord changes

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#67]
- Rename "List of Dataset" to "Datasets"
- Rename "list of Sample" to "Samples"
- Center the numbers
- Use a link color for numbers
- When mouse over the card the entire card should change color (not just part of it)
- Provider edit icon leads to frontpage

**Comment by Anubhav2201** [comment]
Done
Commit: 537b4c534c0039d919c0297adb1de2cf3068fd81
