### ISSUE TITLE
In Add Dataset, resolve the errors

### ISSUE THREAD

**Issue by akshaykokane** [ReneRanzinger/IFEDS-frontend#71]
Erros:

1. API call for paper_meta_info doesn't include paper_id/pubmed id, which is required.
2. After adding new dataset, getting following error at https://glygen.ccrc.uga.edu/ifeds/datasettable page.

![image](https://user-images.githubusercontent.com/30575487/81485590-15297700-921c-11ea-9b73-8be4c4200c5d.png)

**Comment by akshaykokane** [comment]
![image](https://user-images.githubusercontent.com/30575487/81485630-77827780-921c-11ea-9ae8-c7d31d9a6dea.png)

**Comment by Anubhav2201** [comment]
Resolved 
Commit : 1eb69e58cbc67ec8d6ccdbd1e496a4b8d77a89d3

**Comment by akshaykokane** [comment]
Dataset is getting created but still error exists at front end

![image](https://user-images.githubusercontent.com/30575487/81599110-4ded5b80-9396-11ea-904a-ae81cea5a792.png)

**Comment by akshaykokane** [comment]
If we are creating the dataset without the description, the above error is occurring.

**Comment by Anubhav2201** [comment]
Commit: fe8e5e965cc6706e8e0d4350bb00f8e855897477

**Comment by Anubhav2201** [comment]
Commit: 48116af50e7285554e5945dcca3c59ce06f33b2a
@akshaykokane Please check  and if issue still persist then open this ticket
