### ISSUE TITLE
Frontpage review

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#76]
- The Table headings should not be offset from the content (e.g. Authors start xxx pixel right from heading)
- Bug: Go to last page => empty screen
- Bug: Change Rows to 10, sort by Dataset Name => empty screen
- Add a columns with the creation date and make it sortable

**Comment by Anubhav2201** [comment]
Done First Three Part
Commit : 965d1c63cf3d10fb298c096d59d6e7c2047e41de

Creating a new Ticket for 4 point as we still have to wait for backend changes
https://github.com/ReneRanzinger/IFEDS-frontend/issues/79
