### ISSUE TITLE
Change profile

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#84]
•	Validation missing
•	Changes not saved, no error message shown

**Comment by akshaykokane** [comment]
[FIX] Changes not saved
https://github.com/ReneRanzinger/IFEDS-backend/commit/34f9f6c5ab4f776b7ae2da48fb5abd1a878faf59
https://github.com/ReneRanzinger/IFEDS-backend/commit/18adb518adca0271510f715a319e0e4e70b7ee56

**Comment by Anubhav2201** [comment]
Done
Commit: 6d6d9a461b1ffae01725e9f6d56093c90c0a7102
