### ISSUE TITLE
Sample review

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#86]
•	Paging, search should use the same layout as front page
•	Sample type not filled
•	Add sample – validation missing

**Comment by Anubhav2201** [comment]
Done 
Commit: 7f00baa56fc6f0b9e30d0f3ba949c2240d247244 , dc85da329c9fa13c4a1436c14bbeb4fc1ace4db8 , 1d7889b5715060a9025199ef0d00e0f14b669ffc

Yet to resolve:
Paging, search should use the same layout as front page
Opened new ticket: https://github.com/ReneRanzinger/IFEDS-frontend/issues/93
