### ISSUE TITLE
Create user review

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#91]
•	If Iam not logged in I get redirected to main page rather than login
•	Normal users should not have access to this page, only admin
•	Do not use camel case in url, just lowercase and/or underscore
•	No password field (password is created using the reset link)
•	No provider ID (is auto generated)
•	Department, Provider Group, URL and affilitation are optional
•	Rename provider group to Group
•	Rename Affilitation to Institute
•	Change order: Group, Department, Institute, URL
•	No message about success or failure when click on “create user”
•	Password reset link in the email is not working (glygen.ccrc.uga.edu/ifeds/password_reset/Vnpvhu0Vc50EfYdMnBKAWzKobFyZ33) = empty page
•	Change email text to:

Hello {{{FIRSTNAME}}}

An new account has been created for you in the IFEDS data repository. Please use this link to create a new password for your account:
{{{RESTLINK}}}

In case of problems please contact Rene Ranzinger (rene@ccrc.uga.edu).

**Comment by akshaykokane** [comment]
[UPDATE] Email Template at backend
https://github.com/ReneRanzinger/IFEDS-backend/commit/fcb1f72193547b65e2d52a77f111de0fbc672338
