### ISSUE TITLE
User permission review

### ISSUE THREAD

**Issue by ReneRanzinger** [ReneRanzinger/IFEDS-frontend#92]
•	If Iam not logged in I get redirected to main page rather than login
•	Normal users should not have access to this page
•	Columns should be sortable (except “Actions”)
•	Table should have same arrangement than on front page
•	Its very confusion that the row is moving around when click on an action

**Comment by akshaykokane** [comment]
[FIX] for row moving around when click on an action
https://github.com/ReneRanzinger/IFEDS-backend/commit/c8d43dcb3c90fa2d2769534df4667ee137dcce7c

**Comment by Anubhav2201** [comment]
Fixed
Commit : 144a2098c414bb80a9bc269ab82c899b29e4e7f3

New Ticket opened for 
Table should have same arrangement than on front page
https://github.com/ReneRanzinger/IFEDS-frontend/issues/93
